// Everything the shop sells, in one list: books first, then figures, Blu-ray and merch.
// product.html fills itself in from this list (product.html?id=frieren-01),
// and the homepage shelf and Deluxe editions row read it too.
// Books: covers live at images/covers/<id>.jpg. format is only set for deluxe,
// omnibus and hardcover editions (the Deluxe editions row and filter use it).
// Other products have a category, and their photo is images/products/<id>.jpg.
// For them, authors is the maker, and type, size and code fill the details list.
const BOOKS = [
  {
    id: 'frieren-01',
    title: "Frieren: Beyond Journey's End, Vol. 1",
    series: "Frieren: Beyond Journey's End",
    volume: 1,
    authors: 'Kanehito Yamada, Tsukasa Abe',
    price: 11.99,
    publisher: 'VIZ Media',
    pages: 192,
    isbn: '9781974725762',
    genres: ['fantasy', 'drama'],
    status: 'in-stock',
    due: '',
    isNew: true,
    description: "An elf mage who barely noticed her hero party grow old and die finally starts paying attention to the people around her. It's a slow, quiet story about grief, memory and second chances, drawn with a lot of warmth.",
    note: 'I put off starting this for a year because "sad elf" didn\'t sound like my thing. Give it three chapters, it sneaks up on you.'
  },
  {
    id: 'frieren-02',
    title: "Frieren: Beyond Journey's End, Vol. 2",
    series: "Frieren: Beyond Journey's End",
    volume: 2,
    authors: 'Kanehito Yamada, Tsukasa Abe',
    price: 11.99,
    publisher: 'VIZ Media',
    pages: 200,
    isbn: '9781974731213',
    genres: ['fantasy', 'drama'],
    status: 'in-stock',
    due: '',
    isNew: true,
    description: 'Frieren and her young apprentices keep making their slow way north, picking up allies and testing what real strength means along the road. Old memories of the hero party keep surfacing, gently, in the middle of ordinary days.',
    note: ''
  },
  {
    id: 'frieren-03',
    title: "Frieren: Beyond Journey's End, Vol. 3",
    series: "Frieren: Beyond Journey's End",
    volume: 3,
    authors: 'Kanehito Yamada, Tsukasa Abe',
    price: 11.99,
    publisher: 'VIZ Media',
    pages: 200,
    isbn: '9781974731633',
    genres: ['fantasy', 'drama'],
    status: 'in-stock',
    due: '',
    isNew: true,
    description: "The group reaches the mage capital's qualifying exam, where Frieren has to prove her magic is more than just old tricks. It's a good stretch for seeing how differently Fern and Stark have grown since the story began.",
    note: ''
  },
  {
    id: 'frieren-04',
    title: "Frieren: Beyond Journey's End, Vol. 4",
    series: "Frieren: Beyond Journey's End",
    volume: 4,
    authors: 'Kanehito Yamada, Tsukasa Abe',
    price: 11.99,
    publisher: 'VIZ Media',
    pages: 192,
    isbn: '9781974732883',
    genres: ['fantasy', 'drama'],
    status: 'in-stock',
    due: '',
    isNew: true,
    description: "The first-stage exam trials continue, forcing Frieren, Fern and Stark to face mages who fight in ways magic alone can't easily counter. Small character moments keep sneaking in between the battles, which is where this series is at its best.",
    note: ''
  },
  {
    id: 'chainsaw-man-01',
    title: 'Chainsaw Man, Vol. 1',
    series: 'Chainsaw Man',
    volume: 1,
    authors: 'Tatsuki Fujimoto',
    price: 10.99,
    publisher: 'VIZ Media',
    pages: 192,
    isbn: '9781974709939',
    genres: ['action', 'horror'],
    status: 'in-stock',
    due: '',
    isNew: false,
    description: "Denji trades his half of a devil-hunting dog for the world's strangest new job: a devil with a literal chainsaw for a head. It's blood-soaked, very funny, and surprisingly tender once you get past the opening chapters.",
    note: "I recommend this to anyone who says they don't read horror. It gets you laughing before it gets you."
  },
  {
    id: 'chainsaw-man-02',
    title: 'Chainsaw Man, Vol. 2',
    series: 'Chainsaw Man',
    volume: 2,
    authors: 'Tatsuki Fujimoto',
    price: 10.99,
    publisher: 'VIZ Media',
    pages: 192,
    isbn: '9781974709946',
    genres: ['action', 'horror'],
    status: 'in-stock',
    due: '',
    isNew: true,
    description: 'With Public Safety behind him, Denji settles into a stranger, more dangerous kind of normal life as new devils and hunters start circling. The tone swings from slapstick to genuinely unsettling within the same chapter, which is the whole appeal.',
    note: ''
  },
  {
    id: 'spy-x-family-01',
    title: 'Spy x Family, Vol. 1',
    series: 'Spy x Family',
    volume: 1,
    authors: 'Tatsuya Endo',
    price: 10.99,
    publisher: 'VIZ Media',
    pages: 220,
    isbn: '9781974715466',
    genres: ['comedy', 'action'],
    status: 'in-stock',
    due: '',
    isNew: false,
    description: "A spy, an assassin and a telepath end up posing as a family without knowing each other's secrets, all so one kid can get into the right school. It's a warm, ridiculous premise that somehow keeps getting funnier.",
    note: "I've hand-sold this to more parents than any other book on the shelf. Read one chapter at the till and you're hooked."
  },
  {
    id: 'spy-x-family-02',
    title: 'Spy x Family, Vol. 2',
    series: 'Spy x Family',
    volume: 2,
    authors: 'Tatsuya Endo',
    price: 10.99,
    publisher: 'VIZ Media',
    pages: 200,
    isbn: '9781974717248',
    genres: ['comedy', 'action'],
    status: 'in-stock',
    due: '',
    isNew: true,
    description: 'Anya starts at Eden Academy while Loid and Yor keep juggling their double lives around packed lunches and parent-teacher days. The family setup gets even funnier once school politics and classmates are thrown into the mix.',
    note: ''
  },
  {
    id: 'jujutsu-kaisen-01',
    title: 'Jujutsu Kaisen, Vol. 1',
    series: 'Jujutsu Kaisen',
    volume: 1,
    authors: 'Gege Akutami',
    price: 10.99,
    publisher: 'VIZ Media',
    pages: 192,
    isbn: '9781974710027',
    genres: ['action', 'horror'],
    status: 'in-stock',
    due: '',
    isNew: false,
    description: "Yuji swallows a cursed finger to save his friends and ends up sharing his body with a powerful curse, which is about as bad an idea as it sounds. He's pulled straight into Tokyo Jujutsu High's world of exorcists, curses and constant danger.",
    note: ''
  },
  {
    id: 'jujutsu-kaisen-02',
    title: 'Jujutsu Kaisen, Vol. 2',
    series: 'Jujutsu Kaisen',
    volume: 2,
    authors: 'Gege Akutami',
    price: 10.99,
    publisher: 'VIZ Media',
    pages: null,
    isbn: '9781974710034',
    genres: ['action', 'horror'],
    status: 'in-stock',
    due: '',
    isNew: true,
    description: 'Yuji settles into life as a first-year sorcerer while a much bigger, older curse starts stirring in the background. Training missions turn deadly fast, and the series wastes no time raising the stakes.',
    note: ''
  },
  {
    id: 'one-piece-01',
    title: 'One Piece, Vol. 1',
    series: 'One Piece',
    volume: 1,
    authors: 'Eiichiro Oda',
    price: 10.99,
    publisher: 'VIZ Media',
    pages: 208,
    isbn: '9781421545257',
    genres: ['action', 'comedy'],
    status: 'in-stock',
    due: '',
    isNew: false,
    description: "Luffy sets out from his home village with a straw hat, a rubber body, and one very simple dream: to become King of the Pirates. This volume introduces the crew's first real members and the easy, big-hearted adventure tone the whole series runs on.",
    note: ''
  },
  {
    id: 'dandadan-01',
    title: 'Dandadan, Vol. 1',
    series: 'Dandadan',
    volume: 1,
    authors: 'Yukinobu Tatsu',
    price: 11.99,
    publisher: 'VIZ Media',
    pages: 202,
    isbn: '9781974734634',
    genres: ['action', 'comedy'],
    status: 'in-stock',
    due: '',
    isNew: false,
    description: "A believer in aliens and a believer in ghosts make a bet to prove each other wrong, and both of them turn out to be right. What follows is fast, loud and very funny, with fights that escalate further than you'd expect.",
    note: 'This is the one I press into hands when someone says manga has to be serious to be good. Aliens, ghosts, first crushes, somehow it all works.'
  },
  {
    id: 'oshi-no-ko-01',
    title: '[Oshi no Ko], Vol. 1',
    series: '[Oshi no Ko]',
    volume: 1,
    authors: 'Aka Akasaka, Mengo Yokoyari',
    price: 13.50,
    publisher: 'Yen Press',
    pages: 224,
    isbn: '9781975363178',
    genres: ['drama'],
    status: 'in-stock',
    due: '',
    isNew: true,
    description: "A doctor is reborn as the baby of his favorite idol and gets a front-row seat to the entertainment industry's brighter and much darker sides. It starts sweet and then turns into something sharper than you'd expect from the first chapter alone.",
    note: "I didn't expect to gasp out loud on the first chapter, but I did, right here at the counter. Don't let anyone spoil this one for you."
  },
  {
    id: 'witch-hat-atelier-01',
    title: 'Witch Hat Atelier, Vol. 1',
    series: 'Witch Hat Atelier',
    volume: 1,
    authors: 'Kamome Shirahama',
    price: 13.50,
    publisher: 'Kodansha Comics',
    pages: 208,
    isbn: '9781632367709',
    genres: ['fantasy'],
    status: 'in-stock',
    due: '',
    isNew: false,
    description: "Coco has always wanted to do magic, only to learn that the rules everyone told her were true turn out to be wrong. She's taken in by a witch who teaches magic through drawing, in a world where every spell is a picture drawn just right.",
    note: 'Every page looks like a picture book. Read it slowly.'
  },
  {
    id: 'delicious-in-dungeon-01',
    title: 'Delicious in Dungeon, Vol. 1',
    series: 'Delicious in Dungeon',
    volume: 1,
    authors: 'Ryoko Kui',
    price: 14.50,
    publisher: 'Yen Press',
    pages: 192,
    isbn: '9780316473064',
    genres: ['fantasy', 'comedy'],
    status: 'in-stock',
    due: '',
    isNew: false,
    description: "After a dragon wrecks their supplies, Laios and his party decide the fastest way to rescue a lost member is to eat their way through the dungeon's monsters. It's a proper adventure party story that also happens to be a very detailed cookbook.",
    note: "A dungeon crawl that's secretly a cookbook. Don't read it hungry."
  },
  {
    id: 'sakamoto-days-01',
    title: 'Sakamoto Days, Vol. 1',
    series: 'Sakamoto Days',
    volume: 1,
    authors: 'Yuto Suzuki',
    price: 10.99,
    publisher: 'VIZ Media',
    pages: 192,
    isbn: '9781974728947',
    genres: ['action', 'comedy'],
    status: 'in-stock',
    due: '',
    isNew: false,
    description: "A legendary hitman retires for the love of his family, only to find the assassin life doesn't let go that easily. He stays sharp behind the counter of his own corner shop, one chaotic job at a time.",
    note: ''
  },
  {
    id: 'look-back',
    format: 'Hardcover',
    title: 'Look Back',
    series: 'Look Back',
    volume: 1,
    authors: 'Tatsuki Fujimoto',
    price: 16.99,
    publisher: 'VIZ Media',
    pages: 144,
    isbn: '9781974734641',
    genres: ['drama', 'slice-of-life'],
    status: 'in-stock',
    due: '',
    isNew: false,
    description: "Two girls bond over making manga together as kids, then drift into very different lives as they grow up. It's a beautiful, aching one-shot about art, jealousy and friendship that reads in a single sitting.",
    note: 'One book, one sitting. It made me cry on the 46A.'
  },
  {
    id: 'haikyuu-01',
    title: 'Haikyu!!, Vol. 1',
    series: 'Haikyu!!',
    volume: 1,
    authors: 'Haruichi Furudate',
    price: 10.99,
    publisher: 'VIZ Media',
    pages: 192,
    isbn: '9781421591421',
    genres: ['sports', 'comedy'],
    status: 'in-stock',
    due: '',
    isNew: false,
    description: "Shrimpy but determined, Hinata is obsessed with volleyball and desperate to prove that height isn't everything. He lands on the same team as his middle school rival, and the two of them have to figure out how to actually work together.",
    note: ''
  },
  {
    id: 'summer-hikaru-died-01',
    title: 'The Summer Hikaru Died, Vol. 1',
    series: 'The Summer Hikaru Died',
    volume: 1,
    authors: 'Mokumokuren',
    price: 14.50,
    publisher: 'Yen Press',
    pages: 218,
    isbn: '9781975360542',
    genres: ['horror', 'drama'],
    status: 'in-stock',
    due: '',
    isNew: true,
    description: "Yoshiki starts to realize that the boy who came back after Hikaru went missing in the mountains isn't quite Hikaru anymore. It's a quiet, unsettling story about friendship and how far you'd go to hold onto someone.",
    note: 'This one gave me actual chills reading it after closing, alone in the shop. Perfect if you want your horror quiet instead of jumpy.'
  },
  {
    id: 'berserk-deluxe-01',
    format: 'Hardcover',
    title: 'Berserk Deluxe Edition, Vol. 1',
    series: 'Berserk',
    volume: 1,
    authors: 'Kentaro Miura',
    price: 49.99,
    publisher: 'Dark Horse Manga',
    pages: 696,
    isbn: '9781506711980',
    genres: ['action', 'horror', 'fantasy'],
    status: 'pre-order',
    due: '9 Oct',
    isNew: false,
    description: 'Guts wanders the land alone with a sword bigger than he is, and the further you read the more you understand why. This deluxe edition collects the brutal, beautifully drawn opening chapters in one heavyweight hardcover.',
    note: "I've been waiting years for this edition to come back in print. Heavy, gorgeous, and worth every cent of the pre-order."
  },
  {
    id: 'vagabond-01',
    format: 'VIZBIG Edition (3 volumes in 1)',
    title: 'Vagabond VIZBIG Edition, Vol. 1',
    series: 'Vagabond',
    volume: 1,
    authors: 'Takehiko Inoue',
    price: 24.99,
    publisher: 'VIZ Media',
    pages: 728,
    isbn: '9781421520544',
    genres: ['action', 'drama'],
    status: 'pre-order',
    due: '16 Oct',
    isNew: false,
    description: 'A young, violent Shinmen Takezo sets out to become the strongest swordsman alive, starting from absolutely nothing. This VIZBIG edition collects the early volumes of his slow, painful transformation into Miyamoto Musashi.',
    note: ''
  },
  {
    id: 'apothecary-diaries-01',
    title: 'The Apothecary Diaries, Vol. 1',
    series: 'The Apothecary Diaries',
    volume: 1,
    authors: 'Natsu Hyuuga, Nekokurage',
    price: 13.99,
    publisher: 'Square Enix Manga',
    pages: 181,
    isbn: '9781646090709',
    genres: ['drama'],
    status: 'pre-order',
    due: '23 Oct',
    isNew: false,
    description: "Maomao just wants a quiet life in the palace's back rooms, but her sharp eye for poisons keeps dragging her into the middle of every mystery. A clever, curious pharmacist stuck in the inner court turns out to be exactly what the place needed.",
    note: ''
  },
  {
    id: 'blue-period-01',
    title: 'Blue Period, Vol. 1',
    series: 'Blue Period',
    volume: 1,
    authors: 'Tsubasa Yamaguchi',
    price: 13.50,
    publisher: 'Kodansha Comics',
    pages: 224,
    isbn: '9781646511129',
    genres: ['drama', 'slice-of-life'],
    status: 'pre-order',
    due: '30 Oct',
    isNew: false,
    description: 'Yatora is a top student with no real passion for anything, until one painting stops him in his tracks and changes what he wants from life. He throws himself into art school prep with an intensity that surprises everyone, himself included.',
    note: ''
  },
  {
    id: 'berserk-deluxe-02',
    format: 'Deluxe hardcover',
    title: 'Berserk Deluxe Edition, Vol. 2',
    series: 'Berserk',
    volume: 2,
    authors: 'Kentaro Miura',
    price: 49.99,
    publisher: 'Dark Horse Manga',
    pages: 692,
    isbn: '9781506711997',
    genres: ['action', 'horror', 'fantasy'],
    status: 'in-stock',
    due: '',
    isNew: false,
    description: "Guts and the Band of the Hawk push deeper into war and betrayal as Griffith's ambitions start pulling the whole story somewhere darker. This deluxe hardcover keeps Miura's linework enormous on the page, collecting the next stretch of chapters in one heavy volume.",
    note: ''
  },
  {
    id: 'berserk-deluxe-03',
    format: 'Deluxe hardcover',
    title: 'Berserk Deluxe Edition, Vol. 3',
    series: 'Berserk',
    volume: 3,
    authors: 'Kentaro Miura',
    price: 49.99,
    publisher: 'Dark Horse Manga',
    pages: 704,
    isbn: '9781506712000',
    genres: ['action', 'horror', 'fantasy'],
    status: 'pre-order',
    due: '6 Nov',
    isNew: false,
    description: "The eclipse looms as Griffith's choices finally catch up with everyone around him, and this volume covers some of the most brutal chapters in the whole series. Same deluxe hardcover treatment as the rest, so the artwork gets all the room it needs.",
    note: 'This is where the story gets properly brutal, keep tissues nearby. I still think about the ending of this one.'
  },
  {
    id: 'vagabond-02',
    format: 'VIZBIG Edition (3 volumes in 1)',
    title: 'Vagabond VIZBIG Edition, Vol. 2',
    series: 'Vagabond',
    volume: 2,
    authors: 'Takehiko Inoue',
    price: 24.99,
    publisher: 'VIZ Media',
    pages: 632,
    isbn: '9781421522449',
    genres: ['action', 'drama'],
    status: 'in-stock',
    due: '',
    isNew: true,
    description: 'Musashi keeps fighting his way across Japan, sharpening from a reckless brawler into someone who thinks before he swings. This VIZBIG edition collects the next run of volumes in one thick paperback, so you get a lot of story in one go.',
    note: ''
  },
  {
    id: 'monster-perfect-01',
    format: 'Perfect Edition paperback',
    title: 'Monster: The Perfect Edition, Vol. 1',
    series: 'Monster',
    volume: 1,
    authors: 'Naoki Urasawa',
    price: 22.99,
    publisher: 'VIZ Media',
    pages: 426,
    isbn: '9781421569062',
    genres: ['mystery', 'drama'],
    status: 'in-stock',
    due: '',
    isNew: false,
    description: "Dr. Tenma saves a child's life and years later starts to suspect he may have saved a monster instead, kicking off a slow-burn thriller across postwar Europe. This Perfect Edition combines the first two volumes into one hardcover with a cleaner remaster of the art.",
    note: ''
  },
  {
    id: '20th-century-boys-perfect-01',
    format: 'Perfect Edition paperback',
    title: "20th Century Boys: The Perfect Edition, Vol. 1",
    series: '20th Century Boys',
    volume: 1,
    authors: 'Naoki Urasawa',
    price: 22.99,
    publisher: 'VIZ Media',
    pages: 416,
    isbn: '9781421599618',
    genres: ['mystery', 'drama'],
    status: 'pre-order',
    due: '14 Oct',
    isNew: false,
    description: 'A group of childhood friends notice their made-up doomsday plan from grade school starting to come true, decades later and for real. This Perfect Edition hardcover kicks off the sprawling mystery in a bigger format than the original paperbacks.',
    note: ''
  },
  {
    id: 'fullmetal-alchemist-fullmetal-01',
    format: 'Hardcover',
    title: 'Fullmetal Alchemist: Fullmetal Edition, Vol. 1',
    series: 'Fullmetal Alchemist',
    volume: 1,
    authors: 'Hiromu Arakawa',
    price: 27.99,
    publisher: 'VIZ Media',
    pages: 276,
    isbn: '9781421599779',
    genres: ['action', 'fantasy'],
    status: 'in-stock',
    due: '',
    isNew: true,
    description: "Brothers Edward and Alphonse Elric pay the price for breaking alchemy's biggest rule and set out to find a way to get their bodies back. This Fullmetal Edition hardcover reprints the series in a larger format with new colour pages, starting the whole saga from chapter one.",
    note: 'I grew up on the anime, so getting to shelve the manga in hardcover feels like a full circle moment.'
  },
  {
    id: 'uzumaki-deluxe',
    format: 'Hardcover (3-in-1)',
    title: 'Uzumaki (3-in-1 Deluxe Edition)',
    series: 'Uzumaki',
    volume: 1,
    authors: 'Junji Ito',
    price: 32.99,
    publisher: 'VIZ Media',
    pages: 653,
    isbn: '9781421561325',
    genres: ['horror'],
    status: 'in-stock',
    due: '',
    isNew: true,
    description: 'A small town slowly comes undone as spirals start showing up everywhere, in shells, in hair, in the shape of the whole story itself. This deluxe hardcover collects all three volumes of the horror classic in one oversized book.',
    note: 'Junji Ito ruined spirals for me forever. Read it in daylight, trust me.'
  },

  // ---------- Figures, Blu-ray and merch (photos in images/products/) ----------
  {
    id: 'nendoroid-frieren',
    category: 'figures',
    title: 'Nendoroid Frieren',
    series: "Frieren: Beyond Journey's End",
    authors: 'Good Smile Company',
    type: 'Nendoroid figure',
    size: 'Approx. 10 cm tall',
    code: '2367',
    price: 62.99,
    genres: ['fantasy', 'drama'],
    status: 'in-stock',
    due: '',
    isNew: true,
    description: 'This Nendoroid captures Frieren exactly as she looks in the anime, staff and grimoire included, with swappable faces for her usual deadpan calm. She is fully articulated and stands about 10cm tall, ready to pose on a shelf however you like.'
  },
  {
    id: 'pop-up-parade-power',
    category: 'figures',
    title: 'POP UP PARADE Power',
    series: 'Chainsaw Man',
    authors: 'Good Smile Company',
    type: 'POP UP PARADE figure',
    size: 'Approx. 17 cm tall',
    code: '',
    price: 54.99,
    genres: ['action', 'horror'],
    status: 'in-stock',
    due: '',
    isNew: false,
    description: 'Power strikes her usual cocky pose in this POP UP PARADE figure, sculpted straight from her Chainsaw Man design. She stands around 17cm tall on an included stand, no assembly or painting required.'
  },
  {
    id: 'nendoroid-anya-forger-winter',
    category: 'figures',
    title: 'Nendoroid Anya Forger: Winter Clothes Ver.',
    series: 'Spy x Family',
    authors: 'Good Smile Company',
    type: 'Nendoroid figure',
    size: 'Approx. 10 cm tall',
    code: '',
    price: 62.99,
    genres: ['comedy', 'action'],
    status: 'pre-order',
    due: '30 Oct',
    isNew: false,
    description: 'Anya gets bundled up for the cold in this winter-clothes Nendoroid, complete with a heart accessory and a few of her trademark expressions. She stands about 10cm tall and is fully poseable straight out of the box.'
  },
  {
    id: 'nendoroid-satoru-gojo',
    category: 'figures',
    title: 'Nendoroid Satoru Gojo',
    series: 'Jujutsu Kaisen',
    authors: 'Good Smile Company',
    type: 'Nendoroid figure',
    size: 'Approx. 10 cm tall',
    code: '1528',
    price: 59.99,
    genres: ['action', 'horror'],
    status: 'in-stock',
    due: '',
    isNew: false,
    description: 'Gojo comes to Nendoroid size with his sunglasses, alternate hair for the blindfold-off look, and a few face plates to switch between his usual smirk and serious mode. He stands about 10cm tall and includes a stand for display.'
  },
  {
    id: 'pop-up-parade-momo-ayase',
    category: 'figures',
    title: 'POP UP PARADE Momo Ayase',
    series: 'Dandadan',
    authors: 'Good Smile Company',
    type: 'POP UP PARADE figure',
    size: 'Approx. 17 cm tall',
    code: '',
    price: 54.99,
    genres: ['action', 'comedy'],
    status: 'in-stock',
    due: '',
    isNew: true,
    description: 'Momo strikes a confident pose in her school uniform for this Dandadan POP UP PARADE figure. She stands about 17cm tall with a stand included, ready to display straight away.'
  },
  {
    id: 'pop-up-parade-ai-hoshino',
    category: 'figures',
    title: 'POP UP PARADE Ai Hoshino',
    series: '[Oshi no Ko]',
    authors: 'Good Smile Company',
    type: 'POP UP PARADE figure',
    size: 'Approx. 17 cm tall',
    code: 'GSC_WD_05746',
    price: 54.99,
    genres: ['drama'],
    status: 'pre-order',
    due: '30 Oct',
    isNew: false,
    description: 'Ai strikes her idol pose in this POP UP PARADE figure, capturing her [Oshi no Ko] look in fine detail. She stands about 17cm tall and comes on a stand, no glue or paint needed.'
  },
  {
    id: 'frieren-bluray-s1-part1',
    category: 'blu-ray',
    title: "Frieren: Beyond Journey's End Season 1 Part 1 Blu-ray",
    series: "Frieren: Beyond Journey's End",
    authors: 'Crunchyroll',
    type: 'Blu-ray + DVD, 2 discs',
    size: 'Episodes 1 to 16',
    code: '5022366018142',
    price: 54.99,
    genres: ['fantasy', 'drama'],
    status: 'in-stock',
    due: '',
    isNew: true,
    description: "This two-disc set covers the opening arc of Frieren: Beyond Journey's End with both Japanese and English audio options. It runs about 400 minutes and includes clean opening and ending songs plus art cards."
  },
  {
    id: 'chainsaw-man-bluray-vol-01',
    category: 'blu-ray',
    title: 'Chainsaw Man Season 1 Blu-ray',
    series: 'Chainsaw Man',
    authors: 'Crunchyroll',
    type: 'Blu-ray, 2 discs',
    size: 'Episodes 1 to 12',
    code: '',
    price: 74.99,
    genres: ['action', 'horror'],
    status: 'in-stock',
    due: '',
    isNew: false,
    description: 'This limited edition set collects the first season of Chainsaw Man across two Blu-ray discs, packaged in a slipbox with lenticular cover art. It carries Japanese and English audio with English subtitles.'
  },
  {
    id: 'spy-x-family-bluray-s1-part1',
    category: 'blu-ray',
    title: 'Spy x Family Season 1 Part 1 Blu-ray',
    series: 'Spy x Family',
    authors: 'Crunchyroll',
    type: 'Blu-ray + DVD, 4 discs',
    size: 'Episodes 1 to 12',
    code: '',
    price: 54.99,
    genres: ['comedy', 'action'],
    status: 'in-stock',
    due: '',
    isNew: false,
    description: "This four-disc set brings together the first twelve episodes of Spy x Family on two Blu-rays and two DVDs. It was the first English-language home video release for the show's debut season."
  },
  {
    id: 'jujutsu-kaisen-bluray-s1-part1',
    category: 'blu-ray',
    title: 'Jujutsu Kaisen Season 1 Part 1 Blu-ray',
    series: 'Jujutsu Kaisen',
    authors: 'Crunchyroll',
    type: 'Blu-ray + CD, 3 discs',
    size: 'Episodes 1 to 12',
    code: '',
    price: 59.99,
    genres: ['action', 'horror'],
    status: 'in-stock',
    due: '',
    isNew: false,
    description: 'This set covers the first twelve episodes of Jujutsu Kaisen across two Blu-ray discs plus a bonus CD. Extras include a voice actor interview, clean opening and ending songs, and the first chapter of the digital manga.'
  },
  {
    id: 'one-piece-bluray-collection-34',
    category: 'blu-ray',
    title: 'One Piece Collection 34 Blu-ray',
    series: 'One Piece',
    authors: 'Crunchyroll',
    type: 'Blu-ray + DVD, 8 discs',
    size: 'Episodes 819 to 842',
    code: '',
    price: 44.99,
    genres: ['action', 'comedy'],
    status: 'in-stock',
    due: '',
    isNew: false,
    description: 'Collection 34 picks up the story across episodes 819 to 842, spread over eight discs of Blu-ray and DVD. It runs about 600 minutes and is a Crunchyroll home video release.'
  },
  {
    id: 'oshi-no-ko-bluray-s1-collection',
    category: 'blu-ray',
    title: '[Oshi no Ko] Season 1 Blu-ray',
    series: '[Oshi no Ko]',
    authors: 'Sentai Filmworks',
    type: 'Blu-ray, complete series',
    size: 'Episodes 1 to 11',
    code: '816726028163',
    price: 64.99,
    genres: ['drama'],
    status: 'in-stock',
    due: '',
    isNew: false,
    description: "This Sentai Filmworks release gathers the whole first season of [Oshi no Ko] into one collection. It follows Ai and her twins from the idol stage into the entertainment industry's darker side."
  },
  {
    id: 'spy-x-family-loid-plushie',
    category: 'merch',
    title: 'Nendoroid Plus Plushie Loid Forger',
    series: 'Spy x Family',
    authors: 'Good Smile Company',
    type: 'Plush',
    size: 'About 15 cm tall',
    code: '',
    price: 24.99,
    genres: ['comedy', 'action'],
    status: 'in-stock',
    due: '',
    isNew: true,
    description: 'A soft, huggable Nendoroid Plus version of Loid Forger in his usual sharp suit. Anya and Yor come as their own plushies, so you can collect the whole family.'
  },
  {
    id: 'frieren-rubber-mascot-keychain',
    category: 'merch',
    title: 'Frieren Rubber Mascot Keychain',
    series: "Frieren: Beyond Journey's End",
    authors: 'Good Smile Company',
    type: 'Rubber keychain',
    size: 'About 8 cm tall',
    code: '',
    price: 13.99,
    genres: ['fantasy', 'drama'],
    status: 'in-stock',
    due: '',
    isNew: false,
    description: 'This little rubber keychain shrinks Frieren down to Nendoroid Plus size, perfect for clipping onto a bag or pencil case. It is made from soft PVC and stands about 8cm tall.'
  },
  {
    id: 'apothecary-diaries-maomao-acrylic-stand',
    category: 'merch',
    title: 'The Apothecary Diaries Maomao Acrylic Stand',
    series: 'The Apothecary Diaries',
    authors: 'ABYstyle',
    type: 'Acrylic stand',
    size: 'About 10 cm tall, 3 pieces',
    code: '',
    price: 13.99,
    genres: ['drama'],
    status: 'pre-order',
    due: '30 Nov',
    isNew: false,
    description: 'Maomao stands on her own base next to a separate series logo piece, so you can arrange the little display however you like. It is on pre-order and due at the end of November.'
  },
  {
    id: 'sakamoto-days-store-tote-bag',
    category: 'merch',
    title: "Sakamoto Days Sakamoto's Store Tote Bag",
    series: 'Sakamoto Days',
    authors: 'Netflix Shop',
    type: 'Tote bag',
    size: '51 x 36 x 13 cm',
    code: 'SD-101051-0001-SD-SLTB',
    price: 32.99,
    genres: ['action', 'comedy'],
    status: 'in-stock',
    due: '',
    isNew: false,
    description: "This roomy organic cotton tote is printed with artwork from Sakamoto's Store, the family shop at the centre of Sakamoto Days. It has a flat bottom and a sturdy main compartment, so it is just as handy for groceries as it is for a stack of manga volumes."
  },
  {
    id: 'jujutsu-kaisen-shibuya-pin-set',
    category: 'merch',
    title: 'Jujutsu Kaisen Shibuya Incident Pin Set',
    series: 'Jujutsu Kaisen',
    authors: 'TOHO animation',
    type: 'Pin set',
    size: '5 pins, about 5 cm each',
    code: '4570115628674',
    price: 15.99,
    genres: ['action', 'horror'],
    status: 'in-stock',
    due: '',
    isNew: false,
    description: 'This five piece pin set covers the Shibuya Incident arc, with Gojo, Nanami, Itadori, Kugisaki, and Fushiguro each getting their own pin. It was imported direct from a Japan only release, so once the current batch sells out it will not be restocked.'
  },
  {
    id: 'haikyu-season-1-key-art-poster',
    category: 'merch',
    title: 'Haikyu!! Season 1 Key Art Maxi Poster',
    series: 'Haikyu!!',
    authors: 'GB eye',
    type: 'Poster',
    size: '61 x 91.5 cm (24 x 36 in)',
    code: '',
    price: 9.99,
    genres: ['sports', 'comedy'],
    status: 'in-stock',
    due: '',
    isNew: false,
    description: 'This maxi poster shows the Season 1 key art for Haikyu!!, printed on glossy 170gsm paper with a high gloss finish. It arrives rolled up in a sturdy tube, ready to frame or pin straight onto a wall.'
  }
];

// The non-book categories, as they appear in manga.html?cat=... and their names
const CATEGORIES = {
  figures: 'Figures',
  'blu-ray': 'Blu-ray',
  merch: 'Merch'
};
